enabled: true
run:
  disable_downloads: false
  disable_mc: false
  disable_phone: false
  disable_websites: false
settings:
  disable_downloads_interval: 3
  disable_websites_interval: 10
  downloads_path: 
  firefox_profile_path: 
  kill_java_interval: 10
